services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: ./client/streamlit
      dockerfile: Dockerfile
    environment:
      STREAMLIT_API_BASE_URL: http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
