import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--color-bg)",
        "surface-0": "var(--color-surface-0)",
        "surface-1": "var(--color-surface-1)",
        "surface-2": "var(--color-surface-2)",
        surface: "var(--color-surface-1)",
        "soft-surface": "var(--color-surface-0)",
        border: "var(--color-border)",
        "border-strong": "var(--color-border-strong)",
        "border-focus": "var(--color-border-focus)",
        "border-error": "var(--color-border-error)",
        foreground: "var(--color-text-primary)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        "text-disabled": "var(--color-text-disabled)",
        "text-inverse": "var(--color-text-inverse)",
        primary: "var(--color-primary)",
        "primary-hover": "var(--color-primary-hover)",
        "primary-light": "var(--color-primary-light)",
        "primary-muted": "var(--color-primary-muted)",
        success: "var(--color-success)",
        "success-light": "var(--color-success-light)",
        "success-text": "var(--color-success-text)",
        warning: "var(--color-warning)",
        "warning-light": "var(--color-warning-light)",
        "warning-text": "var(--color-warning-text)",
        error: "var(--color-error)",
        "error-light": "var(--color-error-light)",
        "error-text": "var(--color-error-text)",
      },
      fontFamily: {
        sans: ["var(--font-inter)"],
        display: ["var(--font-plus-jakarta)"],
        mono: ["var(--font-geist-mono)"],
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
        10: "40px",
        12: "48px",
        16: "64px",
        20: "80px",
        24: "96px",
        32: "128px",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      fontSize: {
        "display-2xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-md": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-sm": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "heading-xl": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "heading-lg": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "heading-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "heading-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-xl": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-xs": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["13px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "500" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "metric-2xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "metric-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "metric-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "metric-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "mono-lg": ["14px", { lineHeight: "22px", fontWeight: "500" }],
        "mono-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-sm": ["11px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
