DEFAULT_CATEGORY = "All_Beauty"
DEFAULT_PERSONA_VERSION = "v1"
DEFAULT_PERSONA_PROMPT_VERSION = "persona_v1"
DEFAULT_GROQ_MODEL = "qwen/qwen3-32b"

PERSONA_TRAIN_SPLIT = "persona_train"
TASK_A_HOLDOUT_SPLIT = "task_a_holdout"
TASK_B_HOLDOUT_SPLIT = "task_b_holdout"

ALLOWED_TASK_SPLITS = {
    PERSONA_TRAIN_SPLIT,
    TASK_A_HOLDOUT_SPLIT,
    TASK_B_HOLDOUT_SPLIT,
}
